import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const handleClick = () => {
    console.log("placing your order");
    router.push("/product");
  };

  return (
    <main className="p-4">
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Content generated by create next app"
        />
      </Head>

      <nav>
        <Link href="/blog">Blog</Link>
        <Link href="/users">users</Link>
        <Link href="/posts">Posts</Link>
      </nav>

      <h1>Home page</h1>
      <button onClick={handleClick}>Place Order</button>
    </main>
  );
}
